services:
  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./docker/air.dockerfile
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - postdb
    volumes:
      - .:/app

  postdb:
    container_name: postdb
    build: 
      context: .
      dockerfile: ./docker/db.dockerfile
    ports:
      - 5433:5432
    volumes:
      - db-store:/var/lib/postgresql/postdata
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'postgres'
volumes:
  db-store:

networks:
  default:
    name: kcl-back_default
    external: true