services:
  cron:
    container_name: cron
    build:
      context: .
      dockerfile: ./docker/air.dockerfile
    tty: true
    ports:
      - 8000:8000
    volumes:
      - .:/app

#   db:
#     container_name: db
#     build: 
#       context: .
#       dockerfile: ./docker/db.dockerfile
#     ports:
#       - 5432:5432
#     volumes:
#       - db-store:/var/lib/postgresql/data
#     environment:
#       POSTGRES_USER: 'postgres'
#       POSTGRES_PASSWORD: 'postgres'
#       POSTGRES_DB: 'postgres'
# volumes:
#   db-store:

networks:
  default:
    name: kcl-backend_default
    external: true